### PR TITLE
chore(cleanup): Marking snapshot operations as unsupported

### PR DESCRIPTION
**Pull request by rahulKQL**
This change makes all snapshot related operations as unsupported, Also it removes test cases around snapshot operation from integration test cases.

### CODE REVIEW

**Comment by dmitry-fa** [comment]
Question/suggestion: would it make sense to keep unit tests for not supported operations?
At least for the sake of the coverage level. I personally don't have a strong opinion if such tests are required or not.

**Comment by rahulKQL** [comment]
As these are integration tests and lives in altogether different modules. It does not provide any coverage to the original code.

Also, I don't feel we should cover unsupported exception through unit tests.

**Comment by dmitry-fa** [comment]
okay

**Review by dmitry-fa — DISMISSED** [review]
LGTM

**Review by pmakani — DISMISSED** [review]

**Pull request closed without merging**
